---
title: "MULTIV"
author: "Martynka"
date: "3/31/2020"
output: pdf_document
---

```{r}
library(brms)
library(ggplot2)
library(tidyverse)
library(dplyr)
#Load the data:
tbl<- read.table("/Users/mplome/dev/STAGE2/Data/full_data_agg.csv",
                      header = TRUE, sep=",")
```

```{r}
tbl$id <- factor(tbl$sbj_id)
tbl$typ <- factor(tbl$typ)
tbl$age <- factor(tbl$age)
tbl$test_num <- factor(tbl$test_num)

final_with_er = tbl %>% 
  group_by(blok) %>% 
  mutate(error_rate =  error/(error+correct))
#View(final_with_er)


```


```{r}

#final_with_er = write.csv(final_with_er,"/Users/mplome/dev/STAGE2/Data/full_data_agg_with_er.csv" )

#all <- brm(mvbind(error_rate, rt, gain, peak_velocity) ~1+ age + typ + (1|sbj_id),
  #        prior = prior, data = final_with_er)

```

```{r}
summary(all, priors = TRUE, prob = 0.987) #after correcting for multiple comparisons with the nyholt approach, for details see:Stats ->Nyholt

#prior<-c(set_prior("cauchy(0, 10)",class = "b", coef = ""),set_prior("cauchy(0, 10)", class = "Intercept", coef = ""))
```
